image: &default_image rustlang/rust:nightly

version: 2
jobs:
  build:
    docker:
      - image: *default_image
    steps:
      - checkout
      - run: git submodule sync
      - run: git submodule update --init
      - run:
          name: Build
          command: |
            cargo build
            cargo test --bins --tests
            cargo doc --no-deps -p redbpf -p bpf-sys

  publish:
    docker:
      - image: *default_image
    steps:
      - checkout
      - run: git submodule sync
      - run: git submodule update --init
      - run:
          name: Publish package
          command: |
            git config --global url."https://$GITHUB_HTTP_TOKEN:@github.com".insteadOf "https://github.com"
            cargo login $CRATES_KEY
            cd bpf-sys
            cargo publish  
            cd ..
            cargo publish  
            cargo doc --no-deps --release -p redbpf -p bpf-sys

            git config --global user.email "team@redsift.com"
            git config --global user.name "CircleCI bot"
            git clone https://$GITHUB_HTTP_TOKEN:@github.com/redsift/redsift.github.io publish

            rm -rf publish/rust/redbpf/doc
            mkdir -p publish/rust/redbpf/
            cp -r target/doc publish/rust/redbpf/

            cd publish
            git add *
            git commit -a -m '[CI] Update redbpf docs'
            git push


workflows:
  version: 2
  build_publish:
    jobs:
      - build:
          filters:
            tags:
              only: /^v.*/      
      - publish:
          context: org-global
          requires:
            - build
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/    
