image: &default_image rustlang/rust:nightly

version: 2
jobs:
  build:
    docker:
      - image: *default_image
    steps:
      - checkout
      - run:
          name: Build
          command: |
            cargo build
  publish:
    docker:
      - image: *default_image
    steps:
      - checkout      
      - run:
          name: Publish package
          command: |
            cargo login $CRATES_KEY
            cd bpf-sys
            cargo publish  
            cd ..
            cargo publish  

workflows:
  version: 2
  build_publish:
    jobs:
      - build:
          filters:
            tags:
              only: /^v.*/      
      - publish:
          context: org-global
          requires:
            - build
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/    
